### ISSUE TITLE
ux - design ecommerce flow

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/rehash_trash#2]
in terms of checkout logic, there has been a lot of thought already put into the fields here:

https://www.figma.com/file/nIapuABIkKuan4ApGfMLdC/Meredith-navigation-ecommerce?node-id=381%3A9

focus on mobile first.

**Comment by bamboochow** [comment]
@paulchrisluke 
- Added mobile interface design for Store, Checking out (billing, shipping, card info, cart) with alternate cart view that matches current store, and a shopping info screen for address not the same as billing info

Not sure about the store, i don't think it shows enough items and info but wanted to let you see progress and give comments first
